### ISSUE TITLE
Imported the same library twice and some improvements 

### ISSUE THREAD

**Issue by h3uman** [Poojayadav010423/Search-Student-database-using-ID#1]
Hey there! Saw the code.

`from tkinter import *`
`import  tkinter.ttk as ttk` 
Over here, to me, it looks like you've imported the same library twice. If I'm wrong please let me know, and if that's what has happened then please make changes to the code as the extra library will make memory management unnecessarily difficult. Also, it'd be great if we can add students to the database

**Comment by Poojayadav010423** [comment]
First we have imported * values from tkinter then we assigned the variable
tkk to tkinter.ttk for easily calling the tkinter.tkk
Or you can use the tkinter.tkk at the place of tkk

**Comment by h3uman** [comment]
`

**Comment by h3uman** [comment]
I see why, tkinter.ttk has some more features than just tkinter
